### ISSUE TITLE
Unnecessary comments

### ISSUE THREAD

**Issue by gdedi001** [EileenRice/prj-rev-bwfs-dasmoto#2]
Make sure you remove any unnecessary comments 
https://github.com/EileenRice/prj-rev-bwfs-dasmoto/blob/master/Dasmoto01/index.html#L36-L82

**Comment by EileenRice** [comment]
I would have removed them, but I thought it would be a way to communicate with you guys with the line of reasoning.  No worries, I would/will remove for a real client.
